### PR TITLE
Change the default working directory

### PR DESCRIPTION
**Pull request by fkorotkov**
To be consistent with the CLI

See https://github.com/cirruslabs/cirrus-cli/pull/360

### CODE REVIEW

**Comment by edigaryev** [comment]
Wouldn't this cause the problem listed in "Concerns" in https://github.com/cirruslabs/cirrus-ci-docs/issues/814?

**Comment by fkorotkov** [comment]
Yes, but all the build systems I know of use relative paths. I bet there are some that don't but it should be minority. We can postpone merging it until there is a UI for cache invalidation. 🤔  https://github.com/cirruslabs/cirrus-ci-docs/issues/379

**Comment by edigaryev** [comment]
> Yes, but all the build systems I know of use relative paths. I bet there are some that don't but it should be minority. We can postpone merging it until there is a UI for cache invalidation. 🤔 [cirruslabs/cirrus-ci-docs#379](https://github.com/cirruslabs/cirrus-ci-docs/issues/379)

While we're at it, do you think it's possible to detect cache corruption in the agent in an automated fashion?

**Comment by fkorotkov** [comment]
Don't think so. Some easy cases maybe but it's up to a build system to decide if a cache is corrupted. Or if there is a bug in the build system then only human can deduct the corruption.

**Pull request closed without merging**
