### PR TITLE
Rate limit HTTP cache to 10 requests per second

### PR DESCRIPTION
**Pull request by edigaryev**
To alleviate [Please](https://github.com/thought-machine/please) bursts.

### CODE REVIEW

**Comment by edigaryev** [comment]
Apparently the test seems to trigger the https://github.com/golang/go/issues/20960, so I've had to revert it in c4c5e9babc49816e8ed1b068187be4ff88204419.

**Comment by fkorotkov** [comment]
I wonder if it will make sense to simply limit at overall 10 active requests (or 4 per core available) with a semaphore? In this case if there are thousands of requests to download large caches then still every second there will be +10 for 100 seconds.

Having the rate limit in general make sense to not overwhelm I/O. I think 4 requests per core makes sense in this case. What do you think?

**Comment by fkorotkov** [comment]
With the per core limit maybe the test will work 🤔

**Comment by edigaryev** [comment]
> I wonder if it will make sense to simply limit at overall 10 active requests (or 4 per core available) with a semaphore? In this case if there are thousands of requests to download large caches then still every second there will be +10 for 100 seconds.
> 
> Having the rate limit in general make sense to not overwhelm I/O. I think 4 requests per core makes sense in this case. What do you think?

I don't think this has anything to do with cores and with this change we simply set an upper bound on what kind of network activity we're going to tolerate from a single task.

**Comment by edigaryev** [comment]
> With the per core limit maybe the test will work 🤔

This has nothing to do with cores since the test also fails without a rate limiter due to https://github.com/golang/go/issues/20960.

**Comment by fkorotkov** [comment]
I don't see how it "sets an upper bound" since every second you can create 10 new connections.

**Comment by edigaryev** [comment]
> I don't see how it "sets an upper bound" since every second you can create 10 new connections.

Before: HTTP cache client can make an unlimited number of requests per second
Now: HTTP cache client is limited to 10 requests per second

Do we want to limit even more than that?

**Comment by fkorotkov** [comment]
Eventually it can grow to an unlimited amount of requests. Let me check if Bazel is limiting connections somehow.

**Comment by fkorotkov** [comment]
https://github.com/bazelbuild/bazel/blob/62475e738f1206a06dbda0d2638015c2c2fb1c88/src/main/java/com/google/devtools/build/lib/remote/options/RemoteOptions.java#L60-L69

Bazel has the default of 100 connections.

**Comment by fkorotkov** [comment]
My concern here is that if you have large blobs it's faster to download 10 at a time and start doing something with these 10 cache entries then all 500 at once. A build system can start unpacking and using the first 10 caches rather than waiting for all to be downloaded. I think having a per-core limit make sense here.

**Comment by edigaryev** [comment]
> My concern here is that if you have large blobs it's faster to download 10 at a time and start doing something with these 10 cache entries then all 500 at once. A build system can start unpacking and using the first 10 caches rather than waiting for all to be downloaded. I think having a per-core limit make sense here.

I see, this makes sense.

I've replaced the `rate.Limiter` with a buffered channel (aka semaphore) in https://github.com/cirruslabs/cirrus-ci-agent/pull/29/commits/344c040df0fd256dd8a8b767ab03dc486abb5fe2.

**Comment by fkorotkov** [comment]
Suggested to add the limitation on Please side as well: https://github.com/thought-machine/please/issues/1111

**Comment by edigaryev** [comment]
> Maybe use [`golang.org/x/sync/semaphore`](https://godoc.org/golang.org/x/sync/semaphore)?

Good idea, see https://github.com/cirruslabs/cirrus-ci-agent/pull/29/commits/4e8da3caf49a99b0786322d3822aac5f998d401e.

> I also wonder if `NumCPU` can be 0 if container is running with 0.5 CPU. 🤔 Maybe add a lower bound of at minimum 8 requests?

I'm pretty sure it's sane enough to assume it never returns 0. It makes little sense to to so (0.5 CPU is implemented through the process scheduler, by the way) and [there are guards](https://github.com/golang/go/blob/b6feb03b24a75164438c3419c0bc01fef62825a0/src/runtime/os_linux.go#L93-L95) in place for each OS that make sure the minimum value is 1.

And a [lot of code](https://github.com/search?q=runtime.NumCPU&type=Code) would break if this wouldn't be the case.

**Comment by fkorotkov** [comment]
@edigaryev let's change the title post-factum here to remove "10 requests per second"

**Comment by edigaryev** [comment]
> @edigaryev let's change the title post-factum here to remove "10 requests per second"

👌

**Pull request merged**
