### PR TITLE
Ported simplified logic from #129

### PR DESCRIPTION
**Pull request by edigaryev**
The tests currently fail because of https://github.com/cirruslabs/cirrus-ci-agent/pull/130#issuecomment-822782525.

### CODE REVIEW

**Comment by fkorotkov** [comment]
I'm concerned about the failures in `only clone` and `only clone (precreated)`. IMO the precreated directory should not override `CIRRUS_WORKING_DIR`. What do you think?

**Comment by edigaryev** [comment]
> I'm concerned about the failures in `only clone` and `only clone (precreated)`. IMO the precreated directory should not override `CIRRUS_WORKING_DIR`. What do you think?

I'm not sure which override you're talking about since in these tests only `CIRRUS_CLONE_DIR` is defined by the user.

**Comment by fkorotkov** [comment]
> I don't get which override you're talking about? In these tests only CIRRUS_CLONE_DIR is defined by the user.

Yes, and with your logic `CIRRUS_WORKING_DIR` is set to the precreated directory. IMO `CIRRUS_WORKING_DIR` should be set to `$CIRRUS_CLONE_DIR`. 🤔

**Comment by edigaryev** [comment]
> > I don't get which override you're talking about? In these tests only CIRRUS_CLONE_DIR is defined by the user.
> 
> Yes, and with your logic `CIRRUS_WORKING_DIR` is set to the precreated directory. IMO `CIRRUS_WORKING_DIR` should be set to `$CIRRUS_CLONE_DIR`. 🤔

But why'd anyone do this instead of only setting `CIRRUS_WORKING_DIR` correctly in the first place?

And in case someone uses this pattern, they get an empty working directory that can be used to build some artifacts from `CIRRUS_CLONE_DIR`.

**Comment by fkorotkov** [comment]
> But why'd anyone do this instead of only setting CIRRUS_WORKING_DIR correctly in the first place?

Because people can 😅 Let's think about how `CIRRUS_CLONE_DIR` and `CIRRUS_WORKING_DIR` will be described in the [documentation](https://cirrus-ci.org/guide/writing-tasks/#behavioral-environment-variables) and how to explain the defaults. With my changes it will look like #847. In your case I don't feel it's clear.

**Pull request closed without merging**
